version: '2'

services:

  server-3-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: server-3-zookeeper
    ports:
      - "8080:8080"
    environment:
      ZOOKEEPER_CLIENT_PORT: 8080
      ZOOKEEPER_TICK_TIME: 2000

  server-4-kafka-broker:
    image: confluentinc/cp-kafka:latest
    hostname: server-4-kafka-broker
    ports:
      - "1111:1111"
    depends_on:
      - server-3-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: server-3-zookeeper:8080
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://server-4-kafka-broker:1111

  server-1-pong:
    build: './pong'
    hostname: server-1-pong
    depends_on:
      - server-3-zookeeper
      - server-4-kafka-broker

  server-2-ping:
    build: './ping'
    hostname: server-2-ping
    depends_on:
      - server-3-zookeeper
      - server-4-kafka-broker

  gateway:
    build: './gateway'
    hostname: gateway
    depends_on:
      - server-3-zookeeper
      - server-4-kafka-broker
