version: '3'

services:

  server-3-zookeeper:
    image: wurstmeister/zookeeper
    hostname: server-3-zookeeper
    expose:
      - "2181"

  server-4-kafka-broker:
    image: wurstmeister/kafka
    hostname: server-4-kafka-broker
    ports:
      - "1111:1111"
    expose:
      - "9093"
    depends_on:
      - server-3-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: server-3-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://server-4-kafka-broker:9093,OUTSIDE://server-4-kafka-broker:1111
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:1111
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
      - ./:/etc/kafka

  server-1-pong:
    build:
      context: .
      dockerfile: ./pong/Dockerfile
    hostname: server-1-pong
    depends_on:
      - server-3-zookeeper
      - server-4-kafka-broker

  server-2-ping:
    build:
      context: .
      dockerfile: ./ping/Dockerfile
    hostname: server-2-ping
    depends_on:
      - server-3-zookeeper
      - server-4-kafka-broker

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    hostname: gateway
    depends_on:
      - server-3-zookeeper
      - server-4-kafka-broker
